package dsms.client.corba.DSMSApp;


import org.omg.CORBA.portable.IDLEntity;

/**
* dsms/client/corba/DSMSApp/DSMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dsms/client/corba/DSMS.idl
* Tuesday, August 9, 2016 2:17:05 AM EDT
*/

public interface DSMS extends DSMSOperations, org.omg.CORBA.Object, IDLEntity
{
} // interface DSMS
